# Generated by Django 5.0.5 on 2024-05-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='unit_price',
            field=models.PositiveIntegerField(),
        ),
    ]
