# Generated by Django 5.0.5 on 2024-05-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_fooditem_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trayitem',
            old_name='food_name',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='trayitem',
            old_name='store_name',
            new_name='store',
        ),
        migrations.AlterField(
            model_name='trayitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
