# Generated by Django 5.0.5 on 2024-05-09 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_food_name_trayitem_food_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trayitem',
            old_name='food',
            new_name='food_id',
        ),
        migrations.RenameField(
            model_name='trayitem',
            old_name='store',
            new_name='store_id',
        ),
    ]
